import google.generativeai as genai
import base64
from fastapi import HTTPException
import os

GOOGLE_API_KEY = os.getenv("GOOGLE_API_KEY")

async def generate_image_gemini(prompt: str) -> str:
    """
    Generate an image using Gemini 2.5 Flash Image.
    Cost: ~3p per generation vs 1p for GPT Image
    
    Returns:
        Base64 encoded image string
    """
    if not GOOGLE_API_KEY:
        raise HTTPException(status_code=500, detail="Google API key not configured")
    
    genai.configure(api_key=GOOGLE_API_KEY)
    
    try:
        # Use the correct Gemini image model
        model = genai.GenerativeModel('gemini-2.5-flash-image')
        
        response = model.generate_content([prompt])
        
        # Extract image data from response
        if response.parts:
            for part in response.parts:
                if hasattr(part, 'inline_data') and part.inline_data:
                    return base64.b64encode(part.inline_data.data).decode('utf-8')
        
        raise HTTPException(status_code=500, detail="No image generated by Gemini")
        
    except Exception as e:
        print(f"Gemini image generation error: {e}")
        raise HTTPException(status_code=500, detail=f"Gemini image generation failed: {str(e)}")

